### ISSUE TITLE
Doesn't seem to work with Coil AsyncImage

### ISSUE THREAD

**Issue by natanfudge** [mxalbert1996/Zoomable#15]
With this code: 
```kotlin
@Composable
fun App() {
    Zoomable {
        AsyncImage(
            model = "https://images.pexels.com/photos/2253275/pexels-photo-2253275.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
            contentDescription = "image"
        )
    }
}
```

I just get a dog picture with no option to zoom.
Versions:
```
implementation("io.coil-kt:coil-compose:2.0.0-rc02")
implementation("com.mxalbert.zoomable:zoomable:1.4.1")
```

**Comment by mxalbert1996** [comment]
That's expected because your image is smaller than the screen and you are using `ContentScale.Fit` (which is the default value) so the image won't be scaled.
Please refer to the [sample code](https://github.com/mxalbert1996/Zoomable/blob/main/sample/src/main/java/com/mxalbert/zoomable/sample/MainActivity.kt#L81-L91) for how to use Zoomable with Coil.
Note that Coil's API has changed a lot in 2.0.0 so it should be something like:
```Kotlin
val painter = rememberAsyncImagePainter(
    model = ImageRequest.Builder(LocalContext.current)
        .data(imageUrl)
        .size(Size.ORIGINAL)
        .build()
)
if (painter.state is AsyncImagePainter.State.Success) {
    val size = painter.intrinsicSize
    Image(
        painter = painter,
        contentDescription = null,
        modifier = Modifier
            .aspectRatio(size.width / size.height)
            .fillMaxSize()
    )
}
```

**Comment by panpf** [comment]
I recommend a similar image zooming library ZoomImage (https://github.com/panpf/zoomimage).

It perfectly supports Compose Multiplatform and Android View, supports zooming, panning, positioning, rotation, and subsampling of large images. It also integrates image loaders such as sketch, glide, picasso, coil, etc.

The most important thing is that it can zoom large images without memory overflow
